In [ ]:
import os
from collections import Counter
import pandas as pd

import mne
import numpy as np
from moabb.datasets import BNCI2014_001
from moabb.paradigms import MotorImagery

# 数据集
data_dir = os.path.abspath("./../datasets")
mne.set_config("MNE_DATA", data_dir)
dataset = BNCI2014_001()
dataset.download()

print(f"数据集名称 : {dataset.code}")
print(f"被试数量   : {len(dataset.subject_list)}")
print(f"被试编号   : {dataset.subject_list}")

数据集名称 : BNCI2014-001
被试数量   : 9
被试编号   : [1, 2, 3, 4, 5, 6, 7, 8, 9]

```Text
subjects dict
│
└── 1  subject_1 ←── 被试编号作为 dict 
    │
    ├── '0train'  ←── 训练集（session 0）dict
    │   ├── '0': RawArray (第0个run)
    │   ├── '1': RawArray (第1个run)
    │   ├── '2': RawArray (第2个run)
    │   ├── '3': RawArray (第3个run)
    │   ├── '4': RawArray (第4个run)
    │   └── '5': RawArray (第5个run)
    │
    └── '1test'   ←── 测试集（session 1）dict
        ├── '0': RawArray (第0个run)
        ├── '1': RawArray (第1个run)
        ├── '2': RawArray (第2个run)
        ├── '3': RawArray (第3个run)
        ├── '4': RawArray (第4个run)
        └── '5': RawArray (第5个run)

```

In [2]:
# subject/被试
subjects = dataset.get_data(subjects=[1])  # 被试列表
subject_1 = subjects[1]                    # 被试1 Raw 对象

# session/会话
session_train = subject_1['0train']        # 会话0 训练集
session_test = subject_1['1test']          # 会话1 测试集
print(session_train)
print(session_test)
print(len(session_train))
print(len(session_test))

# run/运行
run_0 = session_train['0']                 # 运行0

# raw info
print(f"采样率  : {run_0.info['sfreq']} Hz")
print(f"通道数  : {len(run_0.ch_names)}")
print(f"数据形状: {run_0.get_data().shape}  (channels × samples)")
print(f"通道类型: {run_0.get_channel_types()}")
print(f"通道列表: {run_0.ch_names}")
print(f"通道类型统计: {dict(Counter(run_0.get_channel_types()))}")

{'0': <RawArray | 26 x 96735 (386.9 s), ~19.2 MiB, data loaded>, '1': <RawArray | 26 x 96735 (386.9 s), ~19.2 MiB, data loaded>, '2': <RawArray | 26 x 96735 (386.9 s), ~19.2 MiB, data loaded>, '3': <RawArray | 26 x 96735 (386.9 s), ~19.2 MiB, data loaded>, '4': <RawArray | 26 x 96735 (386.9 s), ~19.2 MiB, data loaded>, '5': <RawArray | 26 x 96735 (386.9 s), ~19.2 MiB, data loaded>}
{'0': <RawArray | 26 x 96735 (386.9 s), ~19.2 MiB, data loaded>, '1': <RawArray | 26 x 96735 (386.9 s), ~19.2 MiB, data loaded>, '2': <RawArray | 26 x 96735 (386.9 s), ~19.2 MiB, data loaded>, '3': <RawArray | 26 x 96735 (386.9 s), ~19.2 MiB, data loaded>, '4': <RawArray | 26 x 96735 (386.9 s), ~19.2 MiB, data loaded>, '5': <RawArray | 26 x 96735 (386.9 s), ~19.2 MiB, data loaded>}
6
6
采样率  : 250.0 Hz
通道数  : 26
数据形状: (26, 96735)  (channels × samples)
通道类型: ['eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eog', 'eog', 'eog', 'stim']
通道列表: ['Fz', 'FC3', 'FC1', 'FCz', 'FC2', 'FC4', 'C5', 'C3', 'C1', 'Cz', 'C2', 'C4', 'C6', 'CP3', 'CP1', 'CPz', 'CP2', 'CP4', 'P1', 'Pz', 'P2', 'POz', 'EOG1', 'EOG2', 'EOG3', 'STI']
通道类型统计: {'eeg': 22, 'eog': 3, 'stim': 1}

In [ ]:
# 获取通道布局:montage对象
montage = run_0.get_montage()          
# 通道名称列表
print(montage.ch_names)           # ['EEG-Fz', 'EEG-0', 'EEG-1', ...]
# 通道数量
print(len(montage.ch_names))      # 22（仅 EEG 通道）
# 获取所有通道的 3D 坐标（单位：米）
positions = montage.get_positions()
import pandas as pd
pd.DataFrame(positions['ch_pos'])

['Fz', 'FC3', 'FC1', 'FCz', 'FC2', 'FC4', 'C5', 'C3', 'C1', 'Cz', 'C2', 'C4', 'C6', 'CP3', 'CP1', 'CPz', 'CP2', 'CP4', 'P1', 'Pz', 'P2', 'POz']
22

,Fz,FC3,FC1,FCz,FC2,FC4,C5,C3,C1,Cz,...,C6,CP3,CP1,CPz,CP2,CP4,P1,Pz,P2,POz
0,-0.001229,-0.061852,-0.035716,-0.001271,0.033131,0.060625,-0.082085,-0.067149,-0.037938,-0.001374,...,0.081653,-0.065472,-0.037425,-0.001525,0.036472,0.064696,-0.030654,-0.001709,0.029886,-0.001900
1,0.093274,0.057133,0.061714,0.063460,0.061828,0.057707,0.019294,0.023358,0.026337,0.027617,...,0.019696,-0.011897,-0.010824,-0.010518,-0.010904,-0.011991,-0.044927,-0.045213,-0.045033,-0.068054
2,0.102639,0.093766,0.117983,0.126572,0.116782,0.093795,0.069490,0.104511,0.129771,0.140199,...,0.069482,0.107778,0.133444,0.141549,0.132812,0.107713,0.119472,0.126673,0.120748,0.095910

In [ ]:
# ============================================================
# 2. 使用 Paradigm 提取特征（epoch）
# ============================================================
# 创建一个运动想象数据处理器样板:提取所有事件
paradigm = MotorImagery()

# get_data() 不区分 train 和 test
# 返回的 X 有 576 个试次（288 + 288），混在一起了。
# 每条记录是一个事件(epoch)
X, labels, metadata = paradigm.get_data(dataset=dataset, subjects=[1])

train_mask = metadata['session'] == '0train'
test_mask  = metadata['session'] == '1test'

X_train    = X[train_mask]
y_train    = np.array(labels)[train_mask]

X_test     = X[test_mask]
y_test     = np.array(labels)[test_mask]

print("=" * 50)
print("Epoch 数据")
print("=" * 50)
print(f"X_train shape : {X_train.shape}")           # (n_trials, n_channels, n_samples)
print(f"labels_train shape : {y_train.shape}")      # (n_trials,)
print(f"标签类别: {np.unique(y_train)}")              # ['feet','left_hand','right_hand','tongue']
print()
print(f"X_test shape : {X_test.shape}")             # (n_trials, n_channels, n_samples)
print(f"labels_test shape : {y_test.shape}")        # (n_trials,)
print(f"标签类别: {np.unique(y_test)}")               # ['feet','left_hand','right_hand','tongue']
print()

Choosing from all possible events

==================================================
Epoch 数据
==================================================
X_train shape : (288, 22, 1001)
labels_train shape : (288,)
标签类别: ['feet' 'left_hand' 'right_hand' 'tongue']

X_test shape : (288, 22, 1001)
labels_test shape : (288,)
标签类别: ['feet' 'left_hand' 'right_hand' 'tongue']

In [39]:
print(metadata.shape)
metadata.head()

(576, 3)

   subject session run
0        1  0train   0
1        1  0train   0
2        1  0train   0
3        1  0train   0
4        1  0train   0

In [30]:
# ============================================================
# 3. 查看各类别样本数量
# ============================================================
print("=" * 50)
print("训练集类别分布")
print("=" * 50)
for label in np.unique(y_train):
    count = np.sum(y_train == label)
    print(f"  {label:12s} : {count} trials")
print()
print("=" * 50)
print("测试集类别分布")
print("=" * 50)
for label in np.unique(y_test):
    count = np.sum(y_test == label)
    print(f"  {label:12s} : {count} trials")
print()

==================================================
训练集类别分布
==================================================
  feet         : 72 trials
  left_hand    : 72 trials
  right_hand   : 72 trials
  tongue       : 72 trials

==================================================
测试集类别分布
==================================================
  feet         : 72 trials
  left_hand    : 72 trials
  right_hand   : 72 trials
  tongue       : 72 trials

In [103]:
import os
from collections import Counter

import mne
import numpy as np
from moabb.datasets import BNCI2014_001
from moabb.paradigms import MotorImagery

# 数据集
data_dir = os.path.abspath("./../datasets")
mne.set_config("MNE_DATA", data_dir)
dataset = BNCI2014_001()
dataset.download()  # 你已经下载过了，重复调用不会重新下载

dataset = BNCI2014_001()
dataset.download()

# ============================================================
# 1. 获取 Raw 对象（字典结构）
# ============================================================
print("=" * 60)
print("1. 获取 Raw 字典")
print("=" * 60)

subjects = dataset.get_data(subjects=[1])

print(f"类型: {type(subjects)}")
print(f"key: {list(subjects.keys())}")
print()

============================================================
1. 获取 Raw 字典
============================================================
类型: <class 'dict'>
key: [1]

In [69]:
# ============================================================
# 2. 取出一个 Raw 对象
# ============================================================
print("=" * 60)
print("2. 取出单个 Raw 对象")
print("=" * 60)

run = subjects[1]['0train']['0'] # 被试1, 训练session, run0

print(f"类型       : {type(run)}")
print(f"采样率     : {run.info['sfreq']} Hz")
print(f"通道数     : {len(run.ch_names)}")
print(f"通道名     : {run.ch_names}")
print(f"采样点数   : {run.n_times}")
print(f"时长       : {run.n_times / run.info['sfreq']:.1f} s")
print(f"数据形状   : {run.get_data().shape}  (channels × samples)")
print()

============================================================
2. 取出单个 Raw 对象
============================================================
类型       : <class 'mne.io.array._array.RawArray'>
采样率     : 250.0 Hz
通道数     : 26
通道名     : ['Fz', 'FC3', 'FC1', 'FCz', 'FC2', 'FC4', 'C5', 'C3', 'C1', 'Cz', 'C2', 'C4', 'C6', 'CP3', 'CP1', 'CPz', 'CP2', 'CP4', 'P1', 'Pz', 'P2', 'POz', 'EOG1', 'EOG2', 'EOG3', 'STI']
采样点数   : 96735
时长       : 386.9 s
数据形状   : (26, 96735)  (channels × samples)

In [75]:
# ============================================================
# 3. 遍历某个被试的所有 Raw
# ============================================================
print("=" * 60)
print("3. 遍历被试1的所有 Raw") # 所有run
print("=" * 60)

subject_data = subjects[1]

for session_name, runs in subject_data.items():
    print(f"\nSession: {session_name}")
    for run_name, run_obj in runs.items():      
        n_samples = run_obj.n_times
        sfreq = run_obj.info['sfreq']
        duration = n_samples / sfreq
        print(f"  Run {run_name}: {len(run_obj.ch_names)} 通道, "
              f"{n_samples} 采样点, {duration:.1f} s")
print()

============================================================
3. 遍历被试1的所有 Raw
============================================================

Session: 0train
  Run 0: 26 通道, 96735 采样点, 386.9 s
  Run 1: 26 通道, 96735 采样点, 386.9 s
  Run 2: 26 通道, 96735 采样点, 386.9 s
  Run 3: 26 通道, 96735 采样点, 386.9 s
  Run 4: 26 通道, 96735 采样点, 386.9 s
  Run 5: 26 通道, 96735 采样点, 386.9 s

Session: 1test
  Run 0: 26 通道, 96735 采样点, 386.9 s
  Run 1: 26 通道, 96735 采样点, 386.9 s
  Run 2: 26 通道, 96735 采样点, 386.9 s
  Run 3: 26 通道, 96735 采样点, 386.9 s
  Run 4: 26 通道, 96735 采样点, 386.9 s
  Run 5: 26 通道, 96735 采样点, 386.9 s

In [79]:
# ============================================================
# 4. 遍历多个被试的所有 Raw
# ============================================================
print("=" * 60)
print("4. 遍历多个被试")
print("=" * 60)

subjects = dataset.get_data(subjects=[1, 2, 3])

all_raws = []
for subject_id, subject_data in subjects.items():
    for session_name, runs in subject_data.items():
        for run_name, raw_obj in runs.items():
            all_raws.append({
                'subject': subject_id,
                'session': session_name,
                'run': run_name,
                'raw': raw_obj,
            })

df = pd.DataFrame(all_raws)
df.head(36)

============================================================
4. 遍历多个被试
============================================================

    subject session run                                                raw
0         1  0train   0  [([[ 3.41796875e-07 -6.34765625e-06 -1.8066406...
1         1  0train   1  [([[-1.56738281e-05 -2.51953125e-05 -2.7294921...
2         1  0train   2  [([[1.08398437e-05 1.66503906e-05 1.03027344e-...
3         1  0train   3  [([[1.19140625e-05 7.95898437e-06 6.83593750e-...
4         1  0train   4  [([[-4.64355469e-05 -5.06347656e-05 -3.9404296...
5         1  0train   5  [([[-1.52832031e-05 -1.34277344e-05 -2.0800781...
6         1   1test   0  [([[5.02929688e-06 1.02539062e-05 5.66406250e-...
7         1   1test   1  [([[-3.27148437e-06 -6.44531250e-06 -1.0449218...
8         1   1test   2  [([[-6.15234375e-06 -1.29394531e-05 -6.7382812...
9         1   1test   3  [([[-3.36914062e-06 -5.71289063e-06 -1.0009765...
10        1   1test   4  [([[-3.17382813e-05 -1.25488281e-05 -9.2285156...
11        1   1test   5  [([[3.99902344e-05 3.28125000e-05 2.87597656e-...
12        2  0train   0  [([[ 7.32421875e-06  8.05664063e-06  1.2255859...
13        2  0train   1  [([[ 9.17968750e-06  7.42187500e-06  8.3496093...
14        2  0train   2  [([[-9.96093750e-06 -6.64062500e-06 -1.9726562...
15        2  0train   3  [([[-2.05078125e-06  1.31835937e-06 -3.1738281...
16        2  0train   4  [([[6.39648437e-06 6.98242188e-06 3.36914062e-...
17        2  0train   5  [([[1.41601562e-06 6.64062500e-06 6.93359375e-...
18        2   1test   0  [([[-2.76367187e-05 -2.49511719e-05 -4.7900390...
19        2   1test   1  [([[-3.41796875e-07 -2.44140625e-06 -2.6220703...
20        2   1test   2  [([[-9.37500000e-06  7.01660156e-05  3.9794921...
21        2   1test   3  [([[9.22851563e-06 1.73828125e-05 6.36230469e-...
22        2   1test   4  [([[ 1.04492187e-05  2.08496094e-05  2.4658203...
23        2   1test   5  [([[ 7.69042969e-05  3.90625000e-07 -2.1630859...
24        3  0train   0  [([[ 6.49414062e-06  3.90625000e-06  9.9121093...
25        3  0train   1  [([[ 6.59179687e-06  1.00585938e-05  1.1621093...
26        3  0train   2  [([[ 1.20117188e-05  1.02050781e-05  3.5156250...
27        3  0train   3  [([[-6.59179687e-06  2.01660156e-05 -1.6113281...
28        3  0train   4  [([[ 6.13769531e-05  6.56250000e-05  5.1416015...
29        3  0train   5  [([[-1.41113281e-05  8.54492187e-06 -8.9843750...
30        3   1test   0  [([[-8.98437500e-06 -5.56640625e-06  1.0351562...
31        3   1test   1  [([[7.37304687e-06 8.10546875e-06 4.88281250e-...
32        3   1test   2  [([[-2.07031250e-05 -5.76171875e-06 -4.3945312...
33        3   1test   3  [([[ 1.03027344e-05 -2.14843750e-06  1.9335937...
34        3   1test   4  [([[ 4.00390625e-06  4.98046875e-06  8.1542968...
35        3   1test   5  [([[-1.65039062e-05 -1.23535156e-05 -1.1132812...

In [78]:

print(f"总共 {len(all_raws)} 个 Raw 对象\n")
for item in all_raws:
    print(f"  Subject {item['subject']} | "
          f"{item['session']} | "
          f"Run {item['run']} | "
          f"{item['raw'].n_times} samples")

print()

总共 36 个 Raw 对象

  Subject 1 | 0train | Run 0 | 96735 samples
  Subject 1 | 0train | Run 1 | 96735 samples
  Subject 1 | 0train | Run 2 | 96735 samples
  Subject 1 | 0train | Run 3 | 96735 samples
  Subject 1 | 0train | Run 4 | 96735 samples
  Subject 1 | 0train | Run 5 | 96735 samples
  Subject 1 | 1test | Run 0 | 96735 samples
  Subject 1 | 1test | Run 1 | 96735 samples
  Subject 1 | 1test | Run 2 | 96735 samples
  Subject 1 | 1test | Run 3 | 96735 samples
  Subject 1 | 1test | Run 4 | 96735 samples
  Subject 1 | 1test | Run 5 | 96735 samples
  Subject 2 | 0train | Run 0 | 96735 samples
  Subject 2 | 0train | Run 1 | 96735 samples
  Subject 2 | 0train | Run 2 | 96735 samples
  Subject 2 | 0train | Run 3 | 96735 samples
  Subject 2 | 0train | Run 4 | 96735 samples
  Subject 2 | 0train | Run 5 | 96735 samples
  Subject 2 | 1test | Run 0 | 96735 samples
  Subject 2 | 1test | Run 1 | 96735 samples
  Subject 2 | 1test | Run 2 | 96735 samples
  Subject 2 | 1test | Run 3 | 96735 samples
  Subject 2 | 1test | Run 4 | 96735 samples
  Subject 2 | 1test | Run 5 | 96735 samples
  Subject 3 | 0train | Run 0 | 96735 samples
  Subject 3 | 0train | Run 1 | 96735 samples
  Subject 3 | 0train | Run 2 | 96735 samples
  Subject 3 | 0train | Run 3 | 96735 samples
  Subject 3 | 0train | Run 4 | 96735 samples
  Subject 3 | 0train | Run 5 | 96735 samples
  Subject 3 | 1test | Run 0 | 96735 samples
  Subject 3 | 1test | Run 1 | 96735 samples
  Subject 3 | 1test | Run 2 | 96735 samples
  Subject 3 | 1test | Run 3 | 96735 samples
  Subject 3 | 1test | Run 4 | 96735 samples
  Subject 3 | 1test | Run 5 | 96735 samples

In [88]:
# ============================================================
# 5. 对 Raw 做预处理
# ============================================================
print("=" * 60)
print("5. 对 Raw 做预处理")
print("=" * 60)

run_0 = subjects[1]['0train']['0'] # 被试1, 训练session, run0
raw = run_0.copy()

# 带通滤波
raw.filter(l_freq=4.0, h_freq=38.0, fir_design='firwin', verbose=False)
print(f"滤波后: {raw.info['highpass']}~{raw.info['lowpass']} Hz")


# 提取事件通道索引和名称
stim_channel = mne.pick_types(raw.info, eeg=False, eog=False, stim=True, exclude=[])
print(f"事件通道索引: {stim_channel}")
stim_channel_names = [raw.ch_names[chan] for chan in stim_channel]  
print(f"事件通道名称: {stim_channel_names}")

# 提取事件信息
events = mne.find_events(raw,stim_channel=['STI'], shortest_event=0)
print(f"事件数: {len(events)}")
print(f"事件信息形状: {events.shape}") # (事件数, 3): (sample：第几个采样点, previous：, event_id)
print(f"事件ID映射: {dataset.metadata.experiment.events}")
print(f"事件名称映射: {dataset.metadata.experiment.class_labels}")
sfreq = raw.info['sfreq']

#  统计每个事件ID的出现次数
unique_ids, counts = np.unique(events[:, 2], return_counts=True)
print("实际的事件ID:")
for uid, cnt in zip(unique_ids, counts):
    print(f"  ID = {uid}, 出现 {cnt} 次")

event_id = {
    'left_hand':  1,
    'right_hand': 2,
    'foot':       3,
    'tongue':     4,
}


events_df = pd.DataFrame(events, columns=['sample', 'previous', 'event_id'])
events_df['event_name'] = events_df['event_id'].map(event_id)

events_df['time_s'] = events_df['sample'] / sfreq  # 事件发生在第几秒
events_df

============================================================
5. 对 Raw 做预处理
============================================================
滤波后: 4.0~38.0 Hz
事件通道索引: [25]
事件通道名称: ['STI']
Finding events on: STI
48 events found on stim channel STI
Event IDs: [1 2 3 4]
事件数: 48
事件信息形状: (48, 3)
事件ID映射: {'left_hand': 1, 'right_hand': 2, 'foot': 3, 'no_control': 0}
事件名称映射: ['left_hand', 'right_hand', 'feet', 'tongue']
实际的事件ID:
  ID = 1, 出现 12 次
  ID = 2, 出现 12 次
  ID = 3, 出现 12 次
  ID = 4, 出现 12 次

    sample  previous  event_id  event_name   time_s
0      250         0         4         NaN    1.000
1     2253         0         3         NaN    9.012
2     4171         0         2         NaN   16.684
3     6123         0         1         NaN   24.492
4     8131         0         1         NaN   32.524
5    10242         0         2         NaN   40.968
6    12159         0         3         NaN   48.636
7    14209         0         4         NaN   56.836
8    16140         0         2         NaN   64.560
9    18138         0         3         NaN   72.552
10   20044         0         1         NaN   80.176
11   21939         0         1         NaN   87.756
12   23911         0         1         NaN   95.644
13   25855         0         4         NaN  103.420
14   27822         0         2         NaN  111.288
15   29942         0         2         NaN  119.768
16   31950         0         1         NaN  127.800
17   34016         0         1         NaN  136.064
18   36052         0         3         NaN  144.208
19   38118         0         1         NaN  152.472
20   40188         0         2         NaN  160.752
21   42268         0         4         NaN  169.072
22   44180         0         4         NaN  176.720
23   46211         0         3         NaN  184.844
24   48164         0         1         NaN  192.656
25   50125         0         4         NaN  200.500
26   52229         0         4         NaN  208.916
27   54233         0         2         NaN  216.932
28   56208         0         4         NaN  224.832
29   58234         0         4         NaN  232.936
30   60305         0         2         NaN  241.220
31   62412         0         1         NaN  249.648
32   64504         0         2         NaN  258.016
33   66595         0         3         NaN  266.380
34   68638         0         3         NaN  274.552
35   70702         0         3         NaN  282.808
36   72722         0         4         NaN  290.888
37   74694         0         3         NaN  298.776
38   76657         0         1         NaN  306.628
39   78582         0         4         NaN  314.328
40   80663         0         2         NaN  322.652
41   82641         0         3         NaN  330.564
42   84631         0         2         NaN  338.524
43   86750         0         3         NaN  347.000
44   88656         0         4         NaN  354.624
45   90584         0         2         NaN  362.336
46   92698         0         3         NaN  370.792
47   94757         0         1         NaN  379.028

In [ ]:
# ============================================================
# 6. 从 Raw 切 Epoch
# ============================================================
print("=" * 60)
print("6. 从 Raw 切 Epoch")
print("=" * 60)



epochs = mne.Epochs(
    raw,
    events=events,
    event_id=event_id,
    tmin=1.0,
    tmax=4.0,
    baseline=None,
    preload=True,
    verbose=False,
)

X = epochs.get_data()
y = epochs.events[:, 2]

print(f"Epoch shape: {X.shape}  (trials, channels, samples)")
print(f"标签类别   : {np.unique(y)}")
for name, eid in event_id.items():
    print(f"  {name:12s}: {np.sum(y == eid)} trials")
print()

============================================================
6. 从 Raw 切 Epoch
============================================================
Epoch shape: (48, 26, 751)  (trials, channels, samples)
标签类别   : [1 2 3 4]
  left_hand   : 12 trials
  right_hand  : 12 trials
  foot        : 12 trials
  tongue      : 12 trials

In [ ]:
# ============================================================
# 7. 拼接同一被试多个 run 的 Raw
# ============================================================
print("=" * 60)
print("7. 拼接多个 Run 的 Raw")
print("=" * 60)

raw_list = []
subject_data = raw_dict[1]['0train']

for run_name in sorted(subject_data.keys()):
    raw_list.append(subject_data[run_name])
    print(f"  加载 Run {run_name}: {subject_data[run_name].n_times} samples")

# MNE 拼接
raw_concat = mne.concatenate_raws(raw_list)
print(f"\n拼接后: {raw_concat.n_times} samples, "
      f"{raw_concat.n_times / raw_concat.info['sfreq']:.1f} s")
print()

In [ ]:
# ============================================================
# 8. Raw 转 NumPy 数组
# ============================================================
print("=" * 60)
print("8. Raw 转 NumPy")
print("=" * 60)

raw_single = raw_dict[1]['0train']['0']

# 方式一：get_data() → (channels, samples)
data = raw_single.get_data()
print(f"get_data()  shape: {data.shape}")

# 方式二：指定通道
picks = mne.pick_channels(raw_single.ch_names, ['EEG-C3', 'EEG-Cz', 'EEG-C4'])
data_picks = raw_single.get_data(picks=picks)
print(f"指定通道   shape: {data_picks.shape}")

# 方式三：指定时间范围
data_window = raw_single.get_data(start=0, stop=1000)
print(f"指定时间窗 shape: {data_window.shape}  (前1000个采样点)")
print()

print("=" * 60)
print("Demo 完成")
print("=" * 60)